# -*- coding: utf-8 -*-
"""ml&es.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r4DJDu10XwNHWwKQEZ-0XiXy5ruasmIp
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score

data=pd.read_csv("/content/Training.csv")
data.head()

print(data['Outcome'].value_counts())
print(data[	'Outcome'].value_counts(normalize=True))

"""data.groupby('Outcome').apply(lambda x: x.sample(n=900))"""

print(data['Outcome'].value_counts())
print(data[	'Outcome'].value_counts(normalize=True))

"""(imbalanced) لتقليل"""

data.isnull().sum()

print(data['Outcome'].value_counts())
print(data[	'Outcome'].value_counts(normalize=True))

data.info()

cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
data[cols] = data[cols].replace(0, np.nan)

"""التخلص من القيمnull   في الاعمده  باستبدالها في  median  الوسيط"""

for col in ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']:
    data[col].fillna(data[col].median(), inplace=True)

"""التخلص من ال outliers"""

cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI', 'Age']

for col in cols:
    Q1 = data[col].quantile(0.25)
    Q3 = data[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    data[col]=np.where(data[col]>upper,upper,np.where(data[col]<lower,lower,data[col]))

plt.figure(figsize=(6,4))
sns.boxplot(x=data["Outcome"], y=data["Glucose"])
plt.title("Glucose vs Outcome")
plt.show()



data[data["Glucose"] > 125]["Outcome"].mean()



plt.figure(figsize=(6,4))
sns.boxplot(x="Outcome", y="BMI", data=data)
plt.title("BMI vs Outcome")
plt.show()



plt.figure(figsize=(6,4))
sns.boxplot(x="Outcome", y="Age", data=data)
plt.title("Age vs Outcome")
plt.show()


plt.figure(figsize=(8,6))
sns.heatmap(data.corr(), annot=True, cmap="coolwarm")
plt.title("Correlation Matrix")
plt.show()



def expert_system(row):
    if row['Glucose'] > 125:
        return 1
    elif row['BMI'] > 35:
        return 1
    elif row['BMI'] > 30 and row['Age'] > 35:
        return 1
    else:
        return 0

X = data.drop("Outcome", axis=1)
y = data["Outcome"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

y_pred = X_test.apply(expert_system, axis=1)

acc = accuracy_score(y_test, y_pred)
prec = precision_score(y_test, y_pred)
rec = recall_score(y_test, y_pred)

print("Accuracy:", acc)
print("Precision:", prec)
print("Recall:", rec)

from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm = confusion_matrix(y_test, y_pred)
disp = ConfusionMatrixDisplay(cm)
disp.plot()
plt.title("Expert System Confusion Matrix")
plt.show()

metrics = ["Accuracy", "Precision", "Recall"]
values = [acc, prec, rec]

plt.bar(metrics, values)
plt.title("Expert System Performance")
plt.show()



dt = DecisionTreeClassifier(
    class_weight="balanced",
    criterion="gini",
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42
)

"""Random Forest"""

rf = RandomForestClassifier(
    class_weight="balanced",
    n_estimators=100,
    max_depth=5,
    min_samples_split=2,
    min_samples_leaf=1,
    max_features="sqrt",
    bootstrap=True,
    random_state=42
)

""" Logistic Regression"""

lr = LogisticRegression(class_weight="balanced",
  max_iter=1000)



dt.fit(X_train, y_train)

rf.fit(X_train, y_train)

lr.fit(X_train, y_train)


y_pred_dt = dt.predict(X_test)

y_pred_rf = rf.predict(X_test)

y_pred_lr = lr.predict(X_test)



def evaluate(y_test, y_pred, name):
    acc = accuracy_score(y_test, y_pred)
    prec = precision_score(y_test, y_pred)
    rec = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)

    print(f"--- {name} ---")
    print("Accuracy:", acc)
    print("Precision:", prec)
    print("Recall:", rec)
    print("F1-score:", f1)
    print()

    return acc, prec, rec,f1

acc_dt, prec_dt, rec_dt,f1_dt= evaluate(y_test, y_pred_dt, "Decision Tree")
acc_rf, prec_rf, rec_rf ,f1_rf = evaluate(y_test, y_pred_rf, "Random Forest")
acc_lr, prec_lr, rec_lr ,f1_lr = evaluate(y_test, y_pred_lr, "Logistic Regression")



models = ["Decision Tree", "Random Forest", "Logistic Regression"]

accuracies = [acc_dt, acc_rf, acc_lr]
precisions = [prec_dt, prec_rf, prec_lr]
recalls = [rec_dt, rec_rf, rec_lr]



plt.figure()
plt.bar(models, accuracies)
plt.title("Accuracy Comparison")
plt.show()



plt.figure()
plt.bar(models, precisions)
plt.title("Precision Comparison")
plt.show()



plt.figure()
plt.bar(models, recalls)
plt.title("Recall Comparison")
plt.show()

train_pred = rf.predict(X_train)
test_pred = rf.predict(X_test)

print("RF Training Accuracy:", accuracy_score(y_train, train_pred))
print("RF Testing Accuracy:", accuracy_score(y_test, test_pred))

train_pred = dt.predict(X_train)
test_pred = dt.predict(X_test)

print("DT Training Accuracy:", accuracy_score(y_train, train_pred))
print("DT Testing Accuracy:", accuracy_score(y_test, test_pred))

train_pred = lr.predict(X_train)
test_pred = lr.predict(X_test)

print("LR Training Accuracy:", accuracy_score(y_train, train_pred))
print("LR Testing Accuracy:", accuracy_score(y_test, test_pred))

from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report, \
            accuracy_score, ConfusionMatrixDisplay,  precision_score,\
            recall_score, f1_score, classification_report
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import GridSearchCV
from xgboost import XGBClassifier


X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(0)
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.2, random_state=42 )

grid_parameters ={
    'n_estimators': [50, 100],
    'learning_rate': [0.1, 0.01, 0.2],
    'max_depth': [3, 4, 5]
}


grid_model = GridSearchCV(
    estimator=XGBClassifier(random_state=0),
    param_grid=grid_parameters,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)
grid_model.fit(X_train, y_train)
print("Best Parameters:,grid_model.best_params_")
print("Best Score:", grid_model.best_score_)
y_pred = grid_model.predict(X_test)

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)
acc = accuracy_score(y_test, y_pred)

print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("Accuracy:", acc)

cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)

disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=[0,1])
disp.plot(cmap="Blues")
plt.show()


best_model = grid_model.best_estimator_


train_pred = best_model.predict(X_train)
test_pred = best_model.predict(X_test)


print("GS Training Accuracy:", accuracy_score(y_train, train_pred))
print("GS Testing Accuracy:", accuracy_score(y_test, test_pred))

from sklearn.model_selection import cross_val_score

scores = cross_val_score(best_model, X, y, cv=5)
print("CV Accuracy:", scores.mean())


import joblib

joblib.dump(dt, "decision_tree_model.pkl")
joblib.dump(rf, "random_forest_model.pkl")
joblib.dump(lr, "logistic_regression_model.pkl")
joblib.dump(best_model, "gboost_model.pkl")



zero_cols = ['Glucose', 'BloodPressure', 'SkinThickness', 'Insulin', 'BMI']
medians = data[zero_cols].median()

joblib.dump(medians, "medians.pkl")


